"""
data.py — All KPI/industry/process data plus small lookup helpers.

This is the ONLY file you edit to add new industries, processes, or KPIs.
No other file needs to change. Everything here is a plain Python dict/list
(no JSON files, no database) so the whole app is just 5 files.
"""
from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass(frozen=True)
class KPI:
    key: str
    name: str
    meaning: str
    why_it_matters: str
    formula: str
    example: str
    unit: str
    better: str
    industries: List[str] = field(default_factory=list)
    improvement_tips: List[str] = field(default_factory=list)
    process: str = ""


import re as _re


def slug(name: str) -> str:
    return _re.sub(r"[^a-z0-9]+", "_", name.lower()).strip("_")


def kpi(name, meaning, why, formula, example, unit, better, industries, tips):
    return {
        "key": slug(name), "name": name, "meaning": meaning,
        "why_it_matters": why, "formula": formula, "example": example,
        "unit": unit, "better": better, "industries": industries,
        "improvement_tips": tips,
    }


INDUSTRIES = [
    "Manufacturing", "Retail", "E-commerce", "Healthcare", "Education",
    "Banking", "Finance", "Insurance", "Hospitality", "Restaurant & Food Service",
    "Logistics", "Supply Chain", "Transportation", "Telecommunications",
    "Information Technology", "Software / SaaS", "Construction", "Real Estate",
    "Energy", "Utilities", "Oil & Gas", "Agriculture", "Pharmaceutical",
    "Automotive", "Aviation", "Media", "Entertainment", "Marketing Agency",
    "Human Resources", "Government", "Non-Profit / NGO",
]

INDUSTRY_DESCRIPTIONS = {
    "Manufacturing": "Companies that turn raw materials into finished physical goods on production lines.",
    "Retail": "Businesses that sell products directly to consumers through physical stores.",
    "E-commerce": "Businesses that sell products or services to consumers primarily online.",
    "Healthcare": "Hospitals, clinics, and providers delivering medical care to patients.",
    "Education": "Schools, colleges, and training providers delivering learning programs.",
    "Banking": "Institutions that take deposits and lend money, such as retail and commercial banks.",
    "Finance": "Firms managing money, investments, and financial planning for clients or themselves.",
    "Insurance": "Companies that pool risk and pay out claims in exchange for premiums.",
    "Hospitality": "Hotels, resorts, and venues focused on guest accommodation and experience.",
    "Restaurant & Food Service": "Businesses that prepare and serve food and beverages to customers.",
    "Logistics": "Companies that plan and move goods from origin to destination efficiently.",
    "Supply Chain": "The end-to-end network of sourcing, producing, and delivering goods.",
    "Transportation": "Businesses that move people or goods by road, rail, sea, or air.",
    "Telecommunications": "Providers of phone, internet, and data connectivity services.",
    "Information Technology": "Companies that build, manage, or support computing systems and infrastructure.",
    "Software / SaaS": "Companies that build and sell software, often via subscription.",
    "Construction": "Businesses that design and build physical structures and infrastructure.",
    "Real Estate": "Businesses involved in buying, selling, renting, or managing property.",
    "Energy": "Companies that generate or supply power, including renewables and fossil fuels.",
    "Utilities": "Providers of essential services like electricity, water, and gas to the public.",
    "Oil & Gas": "Companies involved in extracting, refining, and distributing petroleum products.",
    "Agriculture": "Businesses that grow crops or raise livestock for food and raw materials.",
    "Pharmaceutical": "Companies that research, manufacture, and distribute medicines.",
    "Automotive": "Manufacturers and suppliers of vehicles and vehicle parts.",
    "Aviation": "Airlines and companies involved in air travel and aircraft operations.",
    "Media": "Companies that create and distribute news, publishing, or broadcast content.",
    "Entertainment": "Businesses focused on film, music, gaming, and other leisure content.",
    "Marketing Agency": "Firms that plan and run marketing, advertising, or creative campaigns for clients.",
    "Human Resources": "Firms providing staffing, recruiting, or HR services to other businesses.",
    "Government": "Public-sector bodies delivering services and administration to citizens.",
    "Non-Profit / NGO": "Mission-driven organizations operating without a profit motive.",
}

INDUSTRY_PROCESS_MAPPING = {
    "Manufacturing": ["Production", "Manufacturing", "Inventory Management", "Quality Assurance", "Procurement", "Sales", "Finance"],
    "Retail": ["Sales", "Marketing", "Inventory Management", "Customer Service", "Finance"],
    "E-commerce": ["Sales", "Marketing", "Customer Service", "Inventory Management", "IT", "Finance"],
    "Healthcare": ["Patient Care", "Finance", "Human Resources", "Operations", "Compliance"],
    "Education": ["Human Resources", "Finance", "Administration", "Marketing"],
    "Banking": ["Loans", "Finance", "Risk Management", "Compliance", "Customer Service"],
    "Finance": ["Finance", "Accounting", "Risk Management", "Compliance"],
    "Insurance": ["Risk Management", "Finance", "Customer Service", "Compliance"],
    "Hospitality": ["Sales", "Marketing", "Customer Service", "Human Resources", "Operations"],
    "Restaurant & Food Service": ["Sales", "Inventory Management", "Operations", "Human Resources", "Customer Service"],
    "Logistics": ["Supply Chain", "Operations", "Inventory Management", "Finance"],
    "Supply Chain": ["Supply Chain", "Procurement", "Inventory Management", "Operations"],
    "Transportation": ["Operations", "Supply Chain", "Finance", "Security"],
    "Telecommunications": ["Sales", "Customer Service", "IT", "Operations", "Finance"],
    "Information Technology": ["IT", "Security", "Project Management", "Sales", "Human Resources"],
    "Software / SaaS": ["Sales", "Marketing", "Customer Success", "IT", "Product Development", "Finance"],
    "Construction": ["Project Management", "Procurement", "Operations", "Finance", "Quality Assurance"],
    "Real Estate": ["Sales", "Marketing", "Finance", "Customer Service"],
    "Energy": ["Operations", "Compliance", "Finance", "Quality Assurance"],
    "Utilities": ["Operations", "Compliance", "Customer Service", "Finance"],
    "Oil & Gas": ["Operations", "Compliance", "Procurement", "Finance", "Quality Assurance"],
    "Agriculture": ["Production", "Inventory Management", "Supply Chain", "Finance"],
    "Pharmaceutical": ["R&D", "Manufacturing", "Quality Assurance", "Compliance", "Laboratory", "Pharmacy", "Finance"],
    "Automotive": ["Manufacturing", "Quality Assurance", "Sales", "Procurement", "Supply Chain"],
    "Aviation": ["Operations", "Compliance", "Security", "Customer Service", "Finance"],
    "Media": ["Marketing", "Sales", "Product Development", "Finance"],
    "Entertainment": ["Marketing", "Sales", "Customer Service", "Finance"],
    "Marketing Agency": ["Marketing", "Sales", "Customer Success", "Finance", "Human Resources"],
    "Human Resources": ["Human Resources", "Sales", "Finance", "Compliance"],
    "Government": ["Administration", "Compliance", "Finance", "Human Resources", "Risk Management"],
    "Non-Profit / NGO": ["Finance", "Human Resources", "Administration", "Marketing"],
}

PROCESS_KPIS = {

"Sales": [
    kpi("Revenue", "Total income generated from sales before any expenses are deducted.",
        "The top-line number that everything else in the business is measured against.",
        "Sum of all sales in the period",
        "1,000 units sold at ₹500 = ₹5,00,000 revenue",
        "Currency", "Higher", ["Retail", "E-commerce", "Manufacturing", "SaaS"],
        ["Expand into new customer segments", "Increase average order value", "Improve upsell/cross-sell offers"]),
    kpi("Revenue Growth", "How much revenue has increased or decreased over a period.",
        "Indicates whether the business is expanding, stable, or shrinking.",
        "((Current Revenue - Previous Revenue) / Previous Revenue) × 100",
        "Previous ₹10,00,000, Current ₹12,00,000 → Growth = 20%",
        "%", "Higher", ["Retail", "Manufacturing", "SaaS", "E-commerce"],
        ["Increase customer retention", "Improve pricing strategy", "Upsell existing customers"]),
    kpi("Conversion Rate", "Percentage of prospects or visitors who complete a desired action such as a purchase.",
        "Shows how effectively leads are turned into paying customers.",
        "(Conversions / Total Visitors or Leads) × 100",
        "50 conversions from 2,000 visitors → 2.5%",
        "%", "Higher", ["E-commerce", "Retail", "SaaS", "Real Estate"],
        ["Simplify checkout/signup flow", "Improve landing page relevance", "A/B test calls-to-action"]),
    kpi("Average Order Value", "The average amount spent each time a customer places an order.",
        "Raising AOV grows revenue without needing more customers.",
        "Total Revenue / Number of Orders",
        "₹5,00,000 revenue from 1,000 orders → AOV = ₹500",
        "Currency", "Higher", ["Retail", "E-commerce", "Restaurant & Food Service"],
        ["Bundle complementary products", "Offer volume discounts", "Add upsell prompts at checkout"]),
    kpi("Customer Acquisition Cost", "The average cost to acquire one new paying customer.",
        "Compares directly to Customer Lifetime Value to test if growth is profitable.",
        "(Marketing Spend + Sales Spend) / New Customers Acquired",
        "₹2,00,000 spend / 100 new customers → CAC = ₹2,000",
        "Currency", "Lower", ["SaaS", "E-commerce", "Insurance", "Real Estate"],
        ["Improve targeting to reduce wasted spend", "Invest in referral programs", "Improve lead qualification"]),
    kpi("Sales Cycle Length", "Average time it takes to close a deal from first contact to signed sale.",
        "Shorter cycles mean faster cash flow and higher sales team efficiency.",
        "Total Days to Close (all deals) / Number of Deals Closed",
        "600 total days across 20 deals → 30 days average",
        "Days", "Lower", ["Real Estate", "Insurance", "Information Technology"],
        ["Qualify leads earlier", "Automate follow-ups", "Streamline approval/contract steps"]),
    kpi("Win Rate", "Percentage of sales opportunities that end in a closed-won deal.",
        "Reflects the effectiveness of the sales process and pitch quality.",
        "(Deals Won / Total Opportunities) × 100",
        "20 deals won out of 80 opportunities → 25%",
        "%", "Higher", ["Real Estate", "Information Technology", "Marketing Agency"],
        ["Refine ideal customer profile", "Improve sales training", "Use competitive battle cards"]),
    kpi("Customer Lifetime Value", "Total revenue a business can expect from a single customer over the relationship.",
        "Helps set sustainable acquisition spend and prioritize retention.",
        "Average Order Value × Purchase Frequency × Customer Lifespan (years)",
        "AOV ₹500 × 6 purchases/yr × 3 yrs = ₹9,000",
        "Currency", "Higher", ["SaaS", "E-commerce", "Healthcare", "Banking"],
        ["Improve onboarding experience", "Launch loyalty programs", "Reduce churn"]),
    {**kpi("Monthly Recurring Revenue (MRR)", "Predictable subscription revenue collected every month.",
        "The core growth metric for subscription businesses.",
        "Total Active Subscribers × Average Revenue Per User",
        "500 subscribers × ₹999 ARPU → MRR = ₹4,99,500",
        "Currency", "Higher", ["SaaS", "Software / SaaS", "Telecommunications"],
        ["Reduce churn to protect existing MRR", "Upsell to higher-tier plans", "Improve trial-to-paid conversion"]), "key": "mrr"},
    kpi("CLV to CAC Ratio", "Compares customer lifetime value to acquisition cost to test if growth is profitable.",
        "A ratio of 3:1 or higher is generally considered healthy.",
        "Customer Lifetime Value / Customer Acquisition Cost",
        "CLV ₹9,000 / CAC ₹2,000 → Ratio = 4.5 : 1",
        "Ratio", "Higher", ["SaaS", "E-commerce", "Healthcare"],
        ["Lower CAC through better targeting", "Raise CLV via retention and upsells", "Track by acquisition channel"]),
],

"Marketing": [
    kpi("Website Traffic", "Total number of visits to a website in a period.",
        "A leading indicator of brand reach and top-of-funnel demand.",
        "Count of sessions/visits tracked by analytics tools",
        "45,000 sessions in a month",
        "Count", "Higher", ["E-commerce", "Media", "SaaS"],
        ["Invest in SEO content", "Run targeted ad campaigns", "Improve site speed for retention"]),
    kpi("Click-Through Rate (CTR)", "Percentage of people who click an ad or link after seeing it.",
        "Measures how compelling an ad, email, or headline is.",
        "(Clicks / Impressions) × 100",
        "300 clicks from 15,000 impressions → 2%",
        "%", "Higher", ["Marketing Agency", "Media", "E-commerce"],
        ["Test different ad creatives", "Sharpen the call-to-action", "Improve audience targeting"]),
    kpi("Return on Ad Spend (ROAS)", "Revenue generated for every currency unit spent on advertising.",
        "Tells marketers directly whether ad spend is profitable.",
        "Revenue from Ads / Ad Spend",
        "₹4,00,000 revenue / ₹1,00,000 spend → ROAS = 4",
        "Ratio", "Higher", ["E-commerce", "Retail", "Media"],
        ["Reallocate budget to top-performing channels", "Improve landing page conversion", "Refine audience segments"]),
    kpi("Lead Conversion Rate", "Percentage of marketing leads that become paying customers.",
        "Shows how well marketing and sales are aligned on lead quality.",
        "(Converted Leads / Total Leads) × 100",
        "40 conversions from 500 leads → 8%",
        "%", "Higher", ["Marketing Agency", "SaaS", "Real Estate"],
        ["Improve lead scoring", "Speed up sales follow-up", "Nurture leads with targeted content"]),
    kpi("Email Open Rate", "Percentage of recipients who open a marketing email.",
        "Indicates subject-line and sender-reputation effectiveness.",
        "(Emails Opened / Emails Delivered) × 100",
        "1,200 opens from 10,000 delivered → 12%",
        "%", "Higher", ["E-commerce", "Marketing Agency", "Non-Profit / NGO"],
        ["A/B test subject lines", "Clean and segment the email list", "Send at optimal times"]),
    kpi("Marketing ROI", "Return generated from marketing investment relative to its cost.",
        "The ultimate measure of whether marketing spend is paying off.",
        "((Revenue Attributable to Marketing - Marketing Cost) / Marketing Cost) × 100",
        "₹6,00,000 attributed revenue, ₹2,00,000 cost → ROI = 200%",
        "%", "Higher", ["Marketing Agency", "Retail", "SaaS"],
        ["Improve attribution tracking", "Cut underperforming campaigns", "Double down on high-ROI channels"]),
],

"Finance": [
    kpi("Gross Profit Margin", "Percentage of revenue left after subtracting the cost of goods sold.",
        "Shows core product/service profitability before overheads.",
        "((Revenue - COGS) / Revenue) × 100",
        "Revenue ₹10,00,000, COGS ₹6,00,000 → Margin = 40%",
        "%", "Higher", ["Manufacturing", "Retail", "Pharmaceutical"],
        ["Negotiate better supplier terms", "Reduce production waste", "Optimize pricing"]),
    kpi("Net Profit Margin", "Percentage of revenue remaining after ALL expenses, taxes, and interest.",
        "The definitive bottom-line profitability measure.",
        "(Net Profit / Revenue) × 100",
        "Net profit ₹1,50,000 on ₹10,00,000 revenue → 15%",
        "%", "Higher", ["Restaurant & Food Service", "Retail", "Manufacturing"],
        ["Control operating expenses", "Improve gross margin", "Review non-operating costs"]),
    kpi("Operating Margin", "Percentage of revenue left after operating expenses, excluding tax and interest.",
        "Isolates core operational efficiency from financing decisions.",
        "(Operating Income / Revenue) × 100",
        "Operating income ₹2,00,000 on ₹10,00,000 revenue → 20%",
        "%", "Higher", ["Manufacturing", "Logistics", "Telecommunications"],
        ["Streamline operations", "Automate repetitive processes", "Review vendor contracts"]),
    kpi("EBITDA Margin", "Earnings before interest, tax, depreciation, and amortization, as a % of revenue.",
        "A cleaner comparison of operating performance across companies with different capital structures.",
        "(EBITDA / Revenue) × 100",
        "EBITDA ₹2,50,000 on ₹10,00,000 revenue → 25%",
        "%", "Higher", ["Manufacturing", "Energy", "Telecommunications"],
        ["Improve cost discipline", "Grow high-margin revenue lines", "Reduce fixed-cost base"]),
    kpi("Current Ratio", "A company's ability to pay short-term obligations with short-term assets.",
        "A quick check of short-term financial health and liquidity risk.",
        "Current Assets / Current Liabilities",
        "Assets ₹5,00,000 / Liabilities ₹2,50,000 → 2.0",
        "Ratio", "Higher", ["Banking", "Finance", "Construction"],
        ["Improve receivables collection", "Manage inventory levels", "Renegotiate short-term debt"]),
    kpi("Quick Ratio", "A stricter liquidity measure excluding inventory from current assets.",
        "Shows if a business can meet obligations without relying on selling stock.",
        "(Current Assets - Inventory) / Current Liabilities",
        "(₹5,00,000 - ₹1,00,000) / ₹2,50,000 → 1.6",
        "Ratio", "Higher", ["Retail", "Manufacturing", "Construction"],
        ["Reduce reliance on inventory sales", "Build cash reserves", "Tighten credit terms"]),
    kpi("Cash Flow", "Net amount of cash moving in and out of the business in a period.",
        "Positive cash flow keeps the lights on even if paper profit is low.",
        "Cash Inflows - Cash Outflows",
        "Inflows ₹8,00,000 - Outflows ₹6,50,000 → +₹1,50,000",
        "Currency", "Higher", ["Construction", "Non-Profit / NGO", "Retail"],
        ["Accelerate receivables collection", "Delay non-essential expenses", "Improve payment terms with vendors"]),
    kpi("Working Capital", "Funds available for day-to-day operations.",
        "Insufficient working capital is a leading cause of business failure.",
        "Current Assets - Current Liabilities",
        "₹5,00,000 - ₹2,50,000 = ₹2,50,000",
        "Currency", "Higher", ["Manufacturing", "Construction", "Retail"],
        ["Improve inventory turnover", "Extend payables where possible", "Reduce short-term debt"]),
],

"Accounting": [
    kpi("Accounts Receivable Turnover", "How many times receivables are collected during a period.",
        "High turnover means customers pay quickly, improving cash flow.",
        "Net Credit Sales / Average Accounts Receivable",
        "₹20,00,000 / ₹2,00,000 = 10 times",
        "Times per period", "Higher", ["Manufacturing", "Finance", "Construction"],
        ["Tighten credit policies", "Send timely invoices", "Offer early-payment discounts"]),
    kpi("Accounts Payable Turnover", "How many times a company pays off its suppliers during a period.",
        "Balances maintaining supplier relationships with preserving cash.",
        "Total Supplier Purchases / Average Accounts Payable",
        "₹15,00,000 / ₹1,50,000 = 10 times",
        "Times per period", "Higher", ["Manufacturing", "Retail", "Construction"],
        ["Negotiate favorable payment terms", "Automate invoice processing", "Monitor supplier terms regularly"]),
    kpi("Days Sales Outstanding", "Average number of days it takes to collect payment after a sale.",
        "Lower DSO frees up cash tied up in unpaid invoices.",
        "(Accounts Receivable / Total Credit Sales) × Number of Days",
        "(₹2,00,000 / ₹20,00,000) × 365 ≈ 36.5 days",
        "Days", "Lower", ["Manufacturing", "Construction", "Finance"],
        ["Automate invoice reminders", "Offer multiple payment options", "Review credit terms for risky clients"]),
    kpi("Budget Variance", "Difference between budgeted and actual financial performance.",
        "Highlights where spending or revenue is off-track for corrective action.",
        "((Actual - Budgeted) / Budgeted) × 100",
        "Actual ₹11,00,000 vs Budget ₹10,00,000 → +10%",
        "%", "Lower", ["Government", "Non-Profit / NGO", "Manufacturing"],
        ["Review forecasting assumptions", "Track spend in real time", "Set department-level accountability"]),
],

"Human Resources": [
    kpi("Employee Turnover Rate", "Percentage of employees who leave the organization in a period.",
        "High turnover signals culture, pay, or management problems and raises hiring costs.",
        "(Employees Who Left / Average Total Employees) × 100",
        "12 left / 200 average headcount → 6%",
        "%", "Lower", ["Restaurant & Food Service", "Retail", "Hospitality"],
        ["Improve onboarding and mentoring", "Benchmark compensation regularly", "Act on exit-interview feedback"]),
    kpi("Employee Retention Rate", "Percentage of employees who stay over a period.",
        "The inverse view of turnover; a direct indicator of workplace satisfaction.",
        "((Total Employees - Employees Who Left) / Total Employees) × 100",
        "(200 - 12) / 200 → 94%",
        "%", "Higher", ["Software / SaaS", "Information Technology", "Healthcare"],
        ["Offer growth and career paths", "Recognize and reward performance", "Improve manager training"]),
    kpi("Cost per Hire", "Average total cost to recruit and onboard one new employee.",
        "Helps evaluate the efficiency of recruiting channels and processes.",
        "(Internal + External Recruiting Costs) / Number of Hires",
        "₹5,00,000 total cost / 25 hires → ₹20,000 per hire",
        "Currency", "Lower", ["Information Technology", "Retail", "Manufacturing"],
        ["Strengthen employee referral programs", "Improve job ad targeting", "Streamline the interview process"]),
    kpi("Time to Hire", "Average number of days from job posting to offer acceptance.",
        "Long hiring cycles risk losing top candidates to competitors.",
        "Total Days to Fill All Roles / Number of Roles Filled",
        "600 days / 20 roles → 30 days average",
        "Days", "Lower", ["Information Technology", "Healthcare", "Software / SaaS"],
        ["Simplify the interview stages", "Pre-build candidate pipelines", "Speed up offer approvals"]),
    kpi("Employee Satisfaction Score", "A survey-based measure of how satisfied employees are with their job.",
        "Predicts retention, productivity, and employer brand strength.",
        "Average score from employee survey (e.g. 1-10 scale)",
        "Average of 450 responses = 7.8 / 10",
        "Score", "Higher", ["Software / SaaS", "Hospitality", "Education"],
        ["Run regular pulse surveys", "Act visibly on feedback", "Improve manager-employee communication"]),
    kpi("Revenue per Employee", "Average revenue generated by each employee.",
        "A broad efficiency indicator comparing headcount to output.",
        "Total Revenue / Total Number of Employees",
        "₹5,00,00,000 / 100 employees → ₹5,00,000 per employee",
        "Currency", "Higher", ["Software / SaaS", "Manufacturing", "Marketing Agency"],
        ["Automate low-value manual tasks", "Improve employee training", "Right-size teams to workload"]),
    kpi("Absenteeism Rate", "Percentage of scheduled workdays lost to unplanned employee absence.",
        "High absenteeism often signals disengagement, burnout, or health issues.",
        "(Absent Days / Total Scheduled Workdays) × 100",
        "80 absent days / 5,000 scheduled → 1.6%",
        "%", "Lower", ["Manufacturing", "Healthcare", "Government"],
        ["Improve workplace wellness programs", "Address root causes of burnout", "Offer flexible scheduling"]),
],

"Operations": [
    kpi("Cycle Time", "Total time taken to complete one full cycle of a process from start to finish.",
        "Shorter cycle times mean faster delivery and lower cost per unit.",
        "End Time - Start Time (averaged across units)",
        "Average of 4.5 hours per order processed",
        "Hours/Days", "Lower", ["Manufacturing", "Logistics", "Construction"],
        ["Eliminate non-value-added steps", "Automate handoffs between teams", "Standardize workflows"]),
    kpi("Throughput", "Number of units or transactions a process completes in a given time.",
        "Directly measures operational capacity and output.",
        "Units Completed / Time Period",
        "480 units produced in an 8-hour shift → 60 units/hour",
        "Units/Time", "Higher", ["Manufacturing", "Logistics", "Telecommunications"],
        ["Remove process bottlenecks", "Improve equipment reliability", "Balance workloads across shifts"]),
    kpi("Capacity Utilization", "Percentage of total production capacity actually being used.",
        "Low utilization means idle resources; very high utilization risks burnout/breakdowns.",
        "(Actual Output / Maximum Possible Output) × 100",
        "8,000 units produced / 10,000 max capacity → 80%",
        "%", "Higher", ["Manufacturing", "Energy", "Utilities"],
        ["Improve demand forecasting", "Schedule preventive maintenance", "Balance production across lines"]),
    kpi("Downtime", "Amount of time equipment or a process is not operational when it should be.",
        "Directly reduces throughput and increases cost per unit produced.",
        "Sum of Unplanned Stoppage Time in the period",
        "6.5 hours of downtime in a 160-hour month",
        "Hours", "Lower", ["Manufacturing", "Energy", "Telecommunications"],
        ["Implement predictive maintenance", "Train operators on quick fixes", "Keep critical spare parts in stock"]),
    kpi("Cost per Unit", "Average total cost to produce or deliver one unit.",
        "A core efficiency and pricing benchmark.",
        "Total Operating Cost / Units Produced",
        "₹8,00,000 cost / 10,000 units → ₹80 per unit",
        "Currency", "Lower", ["Manufacturing", "Agriculture", "Logistics"],
        ["Negotiate raw material costs", "Reduce waste and rework", "Improve process automation"]),
    kpi("On-Time Delivery Rate", "Percentage of orders or shipments delivered by the promised date.",
        "A key driver of customer satisfaction and repeat business.",
        "(On-Time Deliveries / Total Deliveries) × 100",
        "950 on-time / 1,000 total → 95%",
        "%", "Higher", ["Logistics", "Manufacturing", "E-commerce"],
        ["Improve demand and route planning", "Add buffer time for high-risk routes", "Strengthen supplier reliability"]),
],

"Manufacturing": [
    kpi("Overall Equipment Effectiveness (OEE)", "Composite score measuring availability, performance, and quality of production equipment.",
        "The gold-standard metric for manufacturing productivity; 85%+ is world class.",
        "Availability % × Performance % × Quality %",
        "90% × 95% × 98% → OEE ≈ 84%",
        "%", "Higher", ["Manufacturing", "Automotive", "Pharmaceutical"],
        ["Reduce unplanned downtime", "Standardize changeover procedures", "Tighten quality control at the source"]),
    kpi("Production Volume", "Total number of units produced in a period.",
        "A direct measure of manufacturing output relative to demand.",
        "Count of finished units produced",
        "12,500 units produced this month",
        "Units", "Higher", ["Manufacturing", "Automotive", "Agriculture"],
        ["Optimize shift scheduling", "Reduce machine changeover time", "Improve supply of raw materials"]),
    kpi("Defect Rate", "Percentage of produced units that fail to meet quality standards.",
        "Directly impacts cost, waste, rework, and customer satisfaction.",
        "(Defective Units / Total Units Produced) × 100",
        "150 defective / 10,000 produced → 1.5%",
        "%", "Lower", ["Manufacturing", "Automotive", "Pharmaceutical"],
        ["Strengthen incoming material inspection", "Improve operator training", "Implement statistical process control"]),
    kpi("Scrap Rate", "Percentage of materials or units discarded as unusable waste.",
        "High scrap rates directly erode gross margin.",
        "(Scrapped Units / Total Units Produced) × 100",
        "80 scrapped / 10,000 produced → 0.8%",
        "%", "Lower", ["Manufacturing", "Automotive", "Construction"],
        ["Improve process precision", "Recalibrate machinery regularly", "Train staff on handling procedures"]),
    kpi("Machine Downtime", "Total time production machinery is not running due to faults or maintenance.",
        "Every hour of downtime is lost throughput and revenue.",
        "Sum of stoppage hours in the period",
        "18 hours of downtime across the month",
        "Hours", "Lower", ["Manufacturing", "Automotive", "Energy"],
        ["Adopt predictive maintenance sensors", "Keep critical spares in stock", "Track and analyze failure patterns"]),
],

"Production": [
    kpi("Production Yield", "Percentage of produced units that meet quality standards on the first pass.",
        "Scrap and rework directly reduce yield and eat into margin.",
        "(Good Units / Total Units Produced) × 100",
        "9,600 good / 10,000 total → 96%",
        "%", "Higher", ["Manufacturing", "Pharmaceutical", "Agriculture"],
        ["Improve process control", "Upgrade aging equipment", "Increase operator training frequency"]),
    kpi("Production Cost per Unit", "Total production cost divided by units produced.",
        "A key lever for pricing decisions and margin management.",
        "Total Production Cost / Units Produced",
        "₹6,00,000 / 10,000 units → ₹60 per unit",
        "Currency", "Lower", ["Manufacturing", "Agriculture", "Automotive"],
        ["Buy raw materials in bulk", "Reduce energy consumption", "Improve labor efficiency"]),
    kpi("Rework Rate", "Percentage of units that need to be reworked before they meet quality standards.",
        "High rework wastes labor and machine time that could go to new output.",
        "(Reworked Units / Total Units Produced) × 100",
        "120 reworked / 10,000 produced → 1.2%",
        "%", "Lower", ["Manufacturing", "Automotive", "Construction"],
        ["Improve first-time-right processes", "Add in-line quality checks", "Standardize work instructions"]),
],

"Inventory Management": [
    kpi("Inventory Turnover", "How many times inventory is sold and replaced over a period.",
        "Low turnover means cash is tied up in slow-moving stock.",
        "COGS / Average Inventory Value",
        "₹40,00,000 COGS / ₹5,00,000 avg inventory → 8 times",
        "Times per period", "Higher", ["Retail", "Manufacturing", "Agriculture"],
        ["Improve demand forecasting", "Discount slow-moving stock", "Tighten reorder points"]),
    kpi("Inventory Accuracy", "How closely recorded inventory matches actual physical stock.",
        "Poor accuracy causes stockouts, overstocking, and lost sales.",
        "(Matching SKU Counts / Total SKUs Counted) × 100",
        "970 matching / 1,000 SKUs counted → 97%",
        "%", "Higher", ["Retail", "E-commerce", "Manufacturing"],
        ["Conduct regular cycle counts", "Use barcode/RFID scanning", "Tighten warehouse process discipline"]),
    kpi("Fill Rate", "Percentage of customer orders fulfilled completely from available stock.",
        "Directly affects customer satisfaction and repeat purchases.",
        "(Orders Fully Shipped / Total Orders) × 100",
        "960 / 1,000 orders fully shipped → 96%",
        "%", "Higher", ["E-commerce", "Retail", "Logistics"],
        ["Improve demand forecasting", "Increase safety stock for key SKUs", "Strengthen supplier reliability"]),
    kpi("Stockout Rate", "Percentage of demand that could not be met due to insufficient stock.",
        "High stockout rates translate directly to lost sales and unhappy customers.",
        "(Stockout Instances / Total Demand Instances) × 100",
        "25 stockouts / 1,000 order instances → 2.5%",
        "%", "Lower", ["Retail", "E-commerce", "Restaurant & Food Service"],
        ["Improve reorder-point calculations", "Diversify suppliers", "Increase buffer stock on top sellers"]),
    kpi("Days Inventory Outstanding", "Average number of days inventory sits before being sold.",
        "Long DIO ties up working capital in unsold stock.",
        "(Average Inventory / COGS) × Number of Days",
        "(₹5,00,000 / ₹40,00,000) × 365 ≈ 46 days",
        "Days", "Lower", ["Retail", "Manufacturing", "Agriculture"],
        ["Run targeted clearance promotions", "Improve purchasing discipline", "Sync procurement with real demand"]),
    kpi("Carrying Cost", "Total cost of holding inventory, including storage, insurance, and depreciation.",
        "Excess carrying cost silently erodes profitability.",
        "(Storage + Insurance + Depreciation + Opportunity Cost) as % of Inventory Value",
        "₹1,00,000 carrying cost on ₹5,00,000 inventory → 20%",
        "%", "Lower", ["Retail", "Manufacturing", "Logistics"],
        ["Reduce excess safety stock", "Improve warehouse space utilization", "Negotiate better storage/insurance rates"]),
],

"Procurement": [
    kpi("Supplier Lead Time", "Average time from placing a purchase order to receiving goods.",
        "Long lead times increase the risk of stockouts and production delays.",
        "Average Days Between PO Placement and Goods Receipt",
        "Average of 12 days across all POs",
        "Days", "Lower", ["Manufacturing", "Construction", "Automotive"],
        ["Diversify supplier base", "Negotiate expedited shipping terms", "Improve demand forecasting accuracy"]),
    kpi("Purchase Price Variance", "Difference between the standard/budgeted cost and actual price paid for goods.",
        "Tracks whether procurement is controlling costs effectively.",
        "(Standard Price - Actual Price) × Quantity Purchased",
        "(₹100 - ₹95) × 10,000 units = ₹50,000 favorable",
        "Currency", "Higher (favorable)", ["Manufacturing", "Construction", "Oil & Gas"],
        ["Negotiate volume discounts", "Lock in long-term supplier contracts", "Benchmark against market pricing regularly"]),
    kpi("Procurement Cost Ratio", "Total procurement department cost as a percentage of total spend managed.",
        "Measures how efficiently the procurement function itself operates.",
        "(Procurement Operating Cost / Total Managed Spend) × 100",
        "₹5,00,000 cost / ₹1,00,00,000 spend → 5%",
        "%", "Lower", ["Manufacturing", "Construction", "Oil & Gas"],
        ["Automate purchase order processing", "Consolidate suppliers", "Use e-procurement platforms"]),
    kpi("Supplier Defect Rate", "Percentage of received goods that fail quality inspection.",
        "High rates signal supplier quality issues that risk production and customer satisfaction.",
        "(Defective Units Received / Total Units Received) × 100",
        "40 defective / 5,000 received → 0.8%",
        "%", "Lower", ["Manufacturing", "Automotive", "Pharmaceutical"],
        ["Tighten supplier quality agreements", "Conduct regular supplier audits", "Diversify to backup suppliers"]),
    kpi("Purchase Order Cycle Time", "Time from purchase requisition to purchase order approval.",
        "Slow approval cycles delay procurement and can cause stockouts.",
        "Average Days from Requisition to PO Approval",
        "Average of 3.5 days per PO",
        "Days", "Lower", ["Manufacturing", "Construction", "Government"],
        ["Automate approval workflows", "Set clear approval thresholds", "Use e-procurement software"]),
],

"Customer Service": [
    kpi("Customer Satisfaction Score (CSAT)", "A direct survey measure of how satisfied customers are with a product or interaction.",
        "A quick pulse-check on service quality and customer happiness.",
        "(Positive Responses / Total Responses) × 100",
        "420 positive / 500 responses → 84%",
        "%", "Higher", ["Retail", "Hospitality", "Telecommunications"],
        ["Coach agents on empathy and resolution speed", "Close the loop on negative feedback", "Simplify the support process"]),
    kpi("Net Promoter Score (NPS)", "Measures customer willingness to recommend a business to others.",
        "A strong predictor of organic growth and brand loyalty.",
        "% Promoters (9-10) - % Detractors (0-6)",
        "60% promoters - 15% detractors = NPS of 45",
        "Score (-100 to 100)", "Higher", ["Software / SaaS", "Retail", "Banking"],
        ["Act on detractor feedback quickly", "Build promoter referral programs", "Survey at key customer touchpoints"]),
    kpi("First Contact Resolution Rate", "Percentage of customer issues resolved in the very first interaction.",
        "Higher FCR means happier customers and lower support costs.",
        "(Issues Resolved on First Contact / Total Issues) × 100",
        "380 / 500 issues resolved on first contact → 76%",
        "%", "Higher", ["Telecommunications", "Retail", "Banking"],
        ["Improve agent training and knowledge base", "Empower agents with more authority", "Route issues to the right specialist"]),
    kpi("Average Response Time", "Average time taken to give a first reply to a customer inquiry.",
        "Fast responses are one of the biggest drivers of customer satisfaction.",
        "Total Response Time / Number of Inquiries",
        "2,000 minutes / 400 inquiries → 5 minutes average",
        "Minutes/Hours", "Lower", ["E-commerce", "Telecommunications", "Software / SaaS"],
        ["Use chatbots for common queries", "Add more staff during peak hours", "Set up smart ticket routing"]),
    kpi("Customer Churn Rate", "Percentage of customers who stop doing business with a company in a period.",
        "High churn undermines growth, no matter how strong acquisition is.",
        "(Customers Lost / Customers at Start of Period) × 100",
        "20 lost / 500 at start → 4%",
        "%", "Lower", ["Software / SaaS", "Telecommunications", "Banking"],
        ["Improve onboarding", "Proactively reach out to at-risk accounts", "Address root causes from exit surveys"]),
    kpi("SLA Compliance Rate", "Percentage of support interactions that meet agreed service-level targets.",
        "Missed SLAs damage trust and can trigger contractual penalties.",
        "(Interactions Meeting SLA / Total Interactions) × 100",
        "470 / 500 met SLA → 94%",
        "%", "Higher", ["Information Technology", "Telecommunications", "Banking"],
        ["Monitor SLA breaches in real time", "Add capacity during predictable spikes", "Automate escalation triggers"]),
],

"Supply Chain": [
    kpi("Perfect Order Rate", "Percentage of orders delivered complete, on time, undamaged, and correctly documented.",
        "The single best composite measure of supply chain reliability.",
        "(Perfect Orders / Total Orders) × 100",
        "920 perfect / 1,000 total → 92%",
        "%", "Higher", ["Logistics", "Supply Chain", "E-commerce"],
        ["Improve order accuracy checks", "Strengthen carrier performance management", "Invest in real-time tracking"]),
    kpi("Supply Chain Cycle Time", "Total time from raw material order to final product delivery.",
        "Shorter cycles improve responsiveness to demand changes.",
        "Sum of Time Across All Supply Chain Stages",
        "Average of 21 days end-to-end",
        "Days", "Lower", ["Logistics", "Manufacturing", "Automotive"],
        ["Improve supplier collaboration", "Reduce handoff delays between stages", "Use demand-driven planning"]),
    kpi("Freight Cost per Unit", "Average shipping cost to move one unit of product.",
        "A major and often overlooked driver of total landed cost.",
        "Total Freight Cost / Units Shipped",
        "₹5,00,000 / 50,000 units → ₹10 per unit",
        "Currency", "Lower", ["Logistics", "Supply Chain", "Manufacturing"],
        ["Consolidate shipments", "Negotiate carrier contracts", "Optimize warehouse-to-customer distances"]),
    kpi("Order Accuracy Rate", "Percentage of orders shipped without errors in items, quantity, or destination.",
        "Errors are costly to fix and damage customer trust.",
        "(Accurate Orders / Total Orders) × 100",
        "985 / 1,000 accurate → 98.5%",
        "%", "Higher", ["Logistics", "E-commerce", "Retail"],
        ["Use barcode scanning at pick/pack", "Improve warehouse layout", "Add double-check steps for high-value orders"]),
],

"Quality Assurance": [
    kpi("First Pass Yield", "Percentage of units that pass quality inspection without any rework.",
        "A pure measure of process capability and consistency.",
        "(Units Passing First Inspection / Total Units Inspected) × 100",
        "940 / 1,000 pass first time → 94%",
        "%", "Higher", ["Manufacturing", "Pharmaceutical", "Automotive"],
        ["Standardize work instructions", "Invest in operator training", "Add in-process quality checkpoints"]),
    kpi("Defect Density", "Number of defects found per unit of output (or per line of code, in software).",
        "A precise, comparable measure of quality across products or releases.",
        "Total Defects / Total Units (or Size Measure)",
        "45 defects / 1,000 units → 0.045 defects per unit",
        "Rate", "Lower", ["Manufacturing", "Information Technology", "Automotive"],
        ["Strengthen root-cause analysis", "Improve design reviews", "Increase test coverage"]),
    kpi("Cost of Quality", "Total cost of ensuring quality, including prevention, inspection, and failure costs.",
        "Helps balance investment in prevention against the cost of defects.",
        "Prevention Cost + Appraisal Cost + Failure Cost",
        "₹1,00,000 + ₹50,000 + ₹2,00,000 = ₹3,50,000",
        "Currency", "Lower", ["Manufacturing", "Pharmaceutical", "Construction"],
        ["Invest more in prevention vs. failure costs", "Reduce warranty claims through better design", "Track cost of quality by category"]),
    kpi("Customer Return Rate", "Percentage of sold units returned by customers due to quality issues.",
        "A direct signal of how quality problems are affecting customers.",
        "(Units Returned / Units Sold) × 100",
        "60 returned / 5,000 sold → 1.2%",
        "%", "Lower", ["Retail", "E-commerce", "Manufacturing"],
        ["Improve pre-shipment quality checks", "Clarify product descriptions/sizing", "Analyze return reasons systematically"]),
],

"IT": [
    kpi("System Uptime", "Percentage of time a system or service is available and operational.",
        "Downtime directly disrupts operations, revenue, and customer trust.",
        "(Total Time - Downtime) / Total Time × 100",
        "Down 4.4 hrs out of 8,760 hrs/year → 99.95% uptime",
        "%", "Higher", ["Information Technology", "Software / SaaS", "Telecommunications"],
        ["Add redundancy and failover systems", "Monitor proactively with alerts", "Run regular disaster-recovery drills"]),
    kpi("Mean Time to Resolve (MTTR)", "Average time taken to resolve an IT incident after it's reported.",
        "Faster resolution minimizes business disruption.",
        "Total Resolution Time / Number of Incidents",
        "1,200 minutes / 40 incidents → 30 minutes average",
        "Minutes/Hours", "Lower", ["Information Technology", "Software / SaaS", "Telecommunications"],
        ["Build better runbooks and playbooks", "Improve monitoring and alerting", "Invest in on-call training"]),
    kpi("IT Cost per User", "Average IT spend allocated to each employee or user supported.",
        "Helps benchmark IT efficiency and budget planning.",
        "Total IT Spend / Number of Users Supported",
        "₹50,00,000 / 500 users → ₹10,000 per user",
        "Currency", "Lower", ["Information Technology", "Software / SaaS", "Government"],
        ["Consolidate software licenses", "Move to cloud where cost-effective", "Standardize hardware refresh cycles"]),
    kpi("Ticket Backlog", "Number of unresolved support tickets at a given time.",
        "A growing backlog signals understaffing or process bottlenecks.",
        "Count of Open, Unresolved Tickets",
        "85 tickets currently open",
        "Count", "Lower", ["Information Technology", "Software / SaaS", "Telecommunications"],
        ["Prioritize tickets by severity", "Add self-service knowledge base", "Balance workload across the team"]),
    kpi("Change Success Rate", "Percentage of IT changes deployed without causing an incident.",
        "Reflects the maturity and safety of change management processes.",
        "(Successful Changes / Total Changes) × 100",
        "96 successful / 100 changes → 96%",
        "%", "Higher", ["Information Technology", "Software / SaaS", "Banking"],
        ["Improve pre-deployment testing", "Use staged rollouts", "Strengthen change review processes"]),
],

"Security": [
    kpi("Incident Response Time", "Average time from detecting a security incident to initiating a response.",
        "Faster response limits the damage and cost of a breach.",
        "Detection-to-Response Time, averaged across incidents",
        "Average of 18 minutes across the quarter",
        "Minutes", "Lower", ["Information Technology", "Banking", "Aviation"],
        ["Automate initial incident triage", "Run regular incident-response drills", "Improve monitoring coverage"]),
    kpi("Number of Security Incidents", "Total count of confirmed security incidents in a period.",
        "Tracks trend of exposure and effectiveness of preventive controls.",
        "Count of Confirmed Incidents",
        "6 confirmed incidents this quarter",
        "Count", "Lower", ["Information Technology", "Banking", "Aviation"],
        ["Strengthen access controls", "Increase employee security training", "Patch vulnerabilities proactively"]),
    kpi("Patch Compliance Rate", "Percentage of systems updated with the latest required security patches.",
        "Unpatched systems are the most common entry point for attacks.",
        "(Patched Systems / Total Systems) × 100",
        "480 / 500 systems patched → 96%",
        "%", "Higher", ["Information Technology", "Banking", "Healthcare"],
        ["Automate patch deployment", "Track patch SLAs by system criticality", "Schedule regular patch windows"]),
],

"Compliance": [
    kpi("Compliance Audit Pass Rate", "Percentage of compliance audits passed without major findings.",
        "Reflects the maturity of internal controls and processes.",
        "(Audits Passed / Total Audits Conducted) × 100",
        "9 passed / 10 audits → 90%",
        "%", "Higher", ["Banking", "Government", "Pharmaceutical"],
        ["Run internal pre-audit checks", "Strengthen documentation practices", "Provide regular compliance training"]),
    kpi("Regulatory Violations", "Number of confirmed regulatory or policy violations in a period.",
        "Directly tied to legal, financial, and reputational risk.",
        "Count of Confirmed Violations",
        "2 violations recorded this year",
        "Count", "Lower", ["Banking", "Government", "Oil & Gas"],
        ["Improve monitoring and controls", "Increase staff training frequency", "Conduct regular internal audits"]),
    kpi("Policy Training Completion Rate", "Percentage of employees who complete required compliance training.",
        "Untrained staff are a major source of avoidable violations.",
        "(Employees Completed / Total Required to Complete) × 100",
        "480 / 500 completed → 96%",
        "%", "Higher", ["Banking", "Government", "Healthcare"],
        ["Automate training reminders", "Make training modules shorter and role-specific", "Tie completion to performance reviews"]),
],

"Project Management": [
    kpi("Schedule Variance", "Difference between planned and actual project progress.",
        "Flags whether a project is ahead of, on, or behind schedule.",
        "Earned Value - Planned Value",
        "₹8,00,000 earned - ₹9,00,000 planned = -₹1,00,000 (behind)",
        "Currency", "Higher (closer to zero/positive)", ["Construction", "Information Technology", "Government"],
        ["Improve milestone tracking", "Reallocate resources to critical-path tasks", "Reassess unrealistic timelines early"]),
    kpi("Cost Variance", "Difference between the budgeted and actual cost of work performed.",
        "Shows whether a project is running over or under budget.",
        "Earned Value - Actual Cost",
        "₹8,00,000 earned - ₹8,50,000 actual cost = -₹50,000 (over budget)",
        "Currency", "Higher (closer to zero/positive)", ["Construction", "Information Technology", "Government"],
        ["Track spend against budget weekly", "Tighten scope-change controls", "Improve cost estimation accuracy"]),
    kpi("On-Time Project Completion Rate", "Percentage of projects completed by their planned deadline.",
        "A key measure of delivery reliability for a project-driven organization.",
        "(Projects Completed On Time / Total Projects) × 100",
        "17 / 20 projects on time → 85%",
        "%", "Higher", ["Construction", "Information Technology", "Marketing Agency"],
        ["Build in schedule buffers for risk", "Improve dependency planning", "Hold regular status reviews"]),
    kpi("Resource Utilization Rate", "Percentage of available team capacity actually spent on billable/project work.",
        "Low utilization wastes capacity; very high utilization risks burnout.",
        "(Hours Worked on Projects / Total Available Hours) × 100",
        "1,280 project hours / 1,600 available hours → 80%",
        "%", "Higher", ["Construction", "Information Technology", "Marketing Agency"],
        ["Improve project scheduling and forecasting", "Balance workload across team members", "Reduce non-billable administrative time"]),
],

"Customer Success": [
    kpi("Net Revenue Retention (NRR)", "Revenue retained and grown from existing customers, including upgrades and downgrades.",
        "Shows whether the existing customer base is a source of growth or decline.",
        "((Starting MRR + Expansion - Contraction - Churn) / Starting MRR) × 100",
        "(₹10,00,000 + ₹1,50,000 - ₹50,000 - ₹40,000) / ₹10,00,000 → 106%",
        "%", "Higher", ["Software / SaaS", "Marketing Agency", "Telecommunications"],
        ["Invest in proactive customer success outreach", "Build a strong upsell/cross-sell motion", "Identify and rescue at-risk accounts early"]),
    kpi("Product Adoption Rate", "Percentage of customers actively using key product features.",
        "Higher adoption correlates strongly with retention and expansion.",
        "(Customers Using Key Feature / Total Customers) × 100",
        "350 / 500 customers using the feature → 70%",
        "%", "Higher", ["Software / SaaS", "Information Technology"],
        ["Improve in-app onboarding", "Send targeted feature-education emails", "Simplify the feature's user experience"]),
    kpi("Customer Health Score", "A composite score predicting a customer's likelihood to renew or churn.",
        "Lets teams prioritize outreach to the accounts most at risk.",
        "Weighted combination of usage, support tickets, and engagement signals",
        "Composite score of 78/100 = 'Healthy'",
        "Score", "Higher", ["Software / SaaS", "Marketing Agency"],
        ["Standardize the scoring model across the team", "Trigger automated alerts for score drops", "Review scores in regular account reviews"]),
    kpi("Time to Value", "Average time a new customer takes to realize meaningful value from a product.",
        "Faster time to value drives higher activation and retention.",
        "Average Days from Signup to First Key Success Milestone",
        "Average of 9 days to first value milestone",
        "Days", "Lower", ["Software / SaaS", "Information Technology"],
        ["Simplify onboarding flows", "Provide guided setup or templates", "Assign dedicated onboarding support"]),
],

"Risk Management": [
    kpi("Risk Exposure Ratio", "Proportion of total assets or capital exposed to identified risk factors.",
        "Helps leadership understand and limit concentration of risk.",
        "Total Value at Risk / Total Assets or Capital",
        "₹2,00,00,000 at risk / ₹10,00,00,000 assets → 20%",
        "%", "Lower", ["Banking", "Insurance", "Finance"],
        ["Diversify the asset/loan portfolio", "Set clear risk-appetite limits", "Increase hedging where appropriate"]),
    kpi("Loss Ratio", "Claims/losses paid out as a percentage of premiums or revenue earned.",
        "Core profitability indicator for insurers and risk-bearing businesses.",
        "(Claims Paid / Premiums Earned) × 100",
        "₹60,00,000 claims / ₹1,00,00,000 premiums → 60%",
        "%", "Lower", ["Insurance", "Banking"],
        ["Improve underwriting criteria", "Invest in fraud detection", "Adjust pricing for high-risk segments"]),
    kpi("Value at Risk (VaR)", "Estimated maximum potential loss over a given time period at a set confidence level.",
        "A standard risk-quantification tool used for capital planning.",
        "Statistical estimate based on portfolio volatility and confidence level",
        "1-day 95% VaR = ₹5,00,000",
        "Currency", "Lower", ["Banking", "Finance", "Insurance"],
        ["Diversify the investment portfolio", "Set and enforce position limits", "Stress-test against extreme scenarios"]),
],

"Loans": [
    kpi("Loan Approval Rate", "Percentage of loan applications that are approved.",
        "Balances growth in lending against credit risk appetite.",
        "(Approved Applications / Total Applications) × 100",
        "320 approved / 400 applications → 80%",
        "%", "Higher (within risk limits)", ["Banking", "Finance"],
        ["Refine credit-scoring models", "Streamline the application process", "Offer tiered products for different risk profiles"]),
    kpi("Non-Performing Loan (NPL) Ratio", "Percentage of total loans that are in default or close to default.",
        "A key indicator of a lender's asset quality and risk exposure.",
        "(Non-Performing Loans / Total Loans Outstanding) × 100",
        "₹5,00,00,000 NPL / ₹1,00,00,00,000 total loans → 5%",
        "%", "Lower", ["Banking", "Finance"],
        ["Tighten underwriting standards", "Improve early-warning monitoring", "Strengthen collections processes"]),
    kpi("Average Loan Processing Time", "Average time from application submission to loan disbursement.",
        "Faster processing improves customer experience and competitiveness.",
        "Total Processing Days / Number of Loans Processed",
        "600 days / 40 loans → 15 days average",
        "Days", "Lower", ["Banking", "Finance"],
        ["Digitize document verification", "Automate credit checks", "Set clear internal SLAs per stage"]),
    kpi("Default Rate", "Percentage of borrowers who fail to meet repayment obligations.",
        "Directly impacts profitability and capital reserves required.",
        "(Defaulted Loans / Total Loans Issued) × 100",
        "25 defaults / 1,000 loans issued → 2.5%",
        "%", "Lower", ["Banking", "Finance"],
        ["Improve credit risk assessment", "Offer restructuring options early", "Monitor at-risk accounts proactively"]),
],

"Pharmacy": [
    kpi("Prescription Fill Rate", "Percentage of prescriptions filled successfully and on time.",
        "Directly affects patient care outcomes and pharmacy revenue.",
        "(Prescriptions Filled / Prescriptions Received) × 100",
        "980 / 1,000 filled → 98%",
        "%", "Higher", ["Pharmaceutical", "Healthcare"],
        ["Improve inventory forecasting for common medications", "Streamline verification workflow", "Add backup supplier agreements"]),
    kpi("Medication Error Rate", "Number of dispensing errors per prescriptions filled.",
        "A critical patient-safety and compliance metric.",
        "(Dispensing Errors / Total Prescriptions Filled) × 1,000",
        "2 errors / 5,000 prescriptions → 0.4 per 1,000",
        "Rate", "Lower", ["Pharmaceutical", "Healthcare"],
        ["Implement barcode verification at dispensing", "Add a double-check step for high-risk drugs", "Invest in pharmacist training"]),
    kpi("Stock Availability Rate", "Percentage of prescribed medications available in stock at time of request.",
        "Stockouts delay treatment and push patients to competitors.",
        "(Prescriptions with Stock Available / Total Prescriptions) × 100",
        "940 / 1,000 with stock available → 94%",
        "%", "Higher", ["Pharmaceutical", "Healthcare"],
        ["Improve demand forecasting", "Set automated reorder points", "Diversify wholesale suppliers"]),
],

"Laboratory": [
    kpi("Sample Turnaround Time", "Average time from sample receipt to results delivery.",
        "Faster turnaround speeds up diagnosis and treatment decisions.",
        "Total Turnaround Time / Number of Samples Processed",
        "4,800 minutes / 400 samples → 12 minutes average",
        "Minutes/Hours", "Lower", ["Healthcare", "Pharmaceutical"],
        ["Automate routine testing equipment", "Prioritize urgent/critical samples", "Reduce manual handoff steps"]),
    kpi("Test Accuracy Rate", "Percentage of lab test results that are accurate and require no re-testing.",
        "Errors here can directly affect patient diagnosis and treatment.",
        "(Accurate Results / Total Results Reported) × 100",
        "995 / 1,000 accurate → 99.5%",
        "%", "Higher", ["Healthcare", "Pharmaceutical"],
        ["Run regular equipment calibration", "Strengthen quality-control sample checks", "Invest in staff certification"]),
    kpi("Lab Utilization Rate", "Percentage of available lab equipment/capacity actually used.",
        "Low utilization wastes expensive equipment investment.",
        "(Actual Tests Run / Maximum Testing Capacity) × 100",
        "3,200 tests run / 4,000 max capacity → 80%",
        "%", "Higher", ["Healthcare", "Pharmaceutical"],
        ["Improve scheduling across shifts", "Balance test load across equipment", "Perform preventive maintenance to avoid downtime"]),
],

"Patient Care": [
    kpi("Patient Satisfaction Score", "Survey-based measure of patient experience and satisfaction with care.",
        "Strongly linked to patient retention and reputation.",
        "Average score from patient satisfaction surveys",
        "Average of 850 responses = 4.4 / 5",
        "Score", "Higher", ["Healthcare"],
        ["Reduce patient wait times", "Improve staff communication training", "Act on patient feedback systematically"]),
    kpi("Average Wait Time", "Average time patients wait before being seen by a provider.",
        "Long waits are consistently the top driver of patient dissatisfaction.",
        "Total Wait Time / Number of Patients",
        "3,600 minutes / 120 patients → 30 minutes average",
        "Minutes", "Lower", ["Healthcare"],
        ["Improve appointment scheduling systems", "Add staff during peak hours", "Use triage to prioritize urgent cases"]),
    kpi("Readmission Rate", "Percentage of patients readmitted within a set period after discharge.",
        "High readmission rates can signal gaps in care quality or discharge planning.",
        "(Readmissions within 30 Days / Total Discharges) × 100",
        "18 readmissions / 300 discharges → 6%",
        "%", "Lower", ["Healthcare"],
        ["Strengthen discharge planning and follow-up", "Improve patient education at discharge", "Coordinate better with outpatient care"]),
    kpi("Bed Occupancy Rate", "Percentage of hospital beds occupied at a given time.",
        "Balances facility utilization against capacity for emergencies.",
        "(Occupied Beds / Total Available Beds) × 100",
        "180 occupied / 200 total beds → 90%",
        "%", "Higher (within safe limits)", ["Healthcare"],
        ["Improve discharge planning to free beds faster", "Balance elective admissions with demand", "Use predictive models for capacity planning"]),
],

"R&D": [
    kpi("R&D Ratio", "Percentage of revenue reinvested into research and development.",
        "A core health metric for innovation-driven and pharma businesses.",
        "(R&D Spend / Revenue) × 100",
        "₹1,50,00,000 R&D / ₹10,00,00,000 revenue → 15%",
        "%", "Higher (within reason)", ["Pharmaceutical", "Software / SaaS", "Automotive"],
        ["Align R&D priorities with market needs", "Track project-level ROI", "Balance core R&D with exploratory research"]),
    kpi("Time to Market", "Average time from concept approval to product launch.",
        "Faster time to market captures opportunity ahead of competitors.",
        "Launch Date - Concept Approval Date (averaged)",
        "Average of 9 months across recent launches",
        "Months", "Lower", ["Pharmaceutical", "Software / SaaS", "Automotive"],
        ["Adopt agile development practices", "Reduce approval bottlenecks", "Run parallel workstreams where possible"]),
    kpi("Innovation Success Rate", "Percentage of R&D projects that result in a successfully launched product.",
        "Reflects the efficiency and focus of the innovation pipeline.",
        "(Successful Launches / Total R&D Projects Initiated) × 100",
        "6 successful / 20 projects initiated → 30%",
        "%", "Higher", ["Pharmaceutical", "Software / SaaS"],
        ["Improve early-stage project screening", "Increase customer feedback loops", "Kill low-potential projects earlier"]),
],

"Engineering": [
    kpi("Deployment Frequency", "How often new code is deployed to production.",
        "Higher frequency generally reflects strong engineering and delivery practices.",
        "Number of Deployments / Time Period",
        "40 deployments in a month",
        "Count/Time", "Higher", ["Software / SaaS", "Information Technology"],
        ["Adopt CI/CD automation", "Break work into smaller releases", "Invest in automated testing"]),
    kpi("Change Failure Rate", "Percentage of deployments that cause a failure requiring a fix or rollback.",
        "A key DevOps metric balancing delivery speed against stability.",
        "(Failed Deployments / Total Deployments) × 100",
        "3 failed / 40 deployments → 7.5%",
        "%", "Lower", ["Software / SaaS", "Information Technology"],
        ["Strengthen automated test coverage", "Use staged/canary rollouts", "Improve code review practices"]),
    kpi("Code Defect Rate", "Number of defects found per unit of code shipped.",
        "Tracks the underlying quality of the engineering process.",
        "Total Defects Found / Lines of Code (or per release)",
        "12 defects per release on average",
        "Rate", "Lower", ["Software / SaaS", "Information Technology"],
        ["Increase automated test coverage", "Improve code review rigor", "Invest in static code analysis tools"]),
],

"Product Development": [
    kpi("Feature Adoption Rate", "Percentage of users who actively use a newly released feature.",
        "Shows whether new investment is translating into real usage.",
        "(Users Using Feature / Total Active Users) × 100",
        "1,200 / 4,000 active users → 30%",
        "%", "Higher", ["Software / SaaS", "Media"],
        ["Improve in-product feature discovery", "Communicate value clearly at launch", "Gather and act on user feedback quickly"]),
    kpi("Release Velocity", "Number of product releases or updates shipped in a period.",
        "Reflects the pace of value delivered to customers.",
        "Count of Releases / Time Period",
        "6 releases shipped this quarter",
        "Count/Time", "Higher", ["Software / SaaS", "Media"],
        ["Adopt smaller, more frequent releases", "Reduce cross-team dependencies", "Automate release pipelines"]),
    kpi("Customer Feedback Score", "Aggregate score of customer sentiment collected via surveys or reviews.",
        "Guides product prioritization based on real user sentiment.",
        "Average Score from Feedback Surveys / Reviews",
        "Average of 4.2 / 5 across 300 reviews",
        "Score", "Higher", ["Software / SaaS", "Media", "Entertainment"],
        ["Close the feedback loop with users", "Prioritize roadmap by feedback themes", "Segment feedback by user type"]),
],

"Administration": [
    kpi("Administrative Cost Ratio", "Administrative costs as a percentage of total operating expenses.",
        "High ratios can signal bloated overhead relative to core operations.",
        "(Administrative Costs / Total Operating Expenses) × 100",
        "₹20,00,000 / ₹1,00,00,000 → 20%",
        "%", "Lower", ["Government", "Non-Profit / NGO", "Education"],
        ["Automate routine administrative tasks", "Consolidate redundant administrative roles", "Review vendor contracts regularly"]),
    kpi("Process Cycle Time", "Average time to complete a standard administrative process end-to-end.",
        "Long cycle times slow down the whole organization.",
        "End Time - Start Time (averaged across process instances)",
        "Average of 3.2 days per process instance",
        "Days", "Lower", ["Government", "Non-Profit / NGO", "Education"],
        ["Digitize paper-based workflows", "Remove redundant approval steps", "Set clear process SLAs"]),
    kpi("Document Turnaround Time", "Average time to process and return a document or request.",
        "A key driver of stakeholder satisfaction in administrative-heavy organizations.",
        "Total Turnaround Time / Number of Documents Processed",
        "480 hours / 160 documents → 3 hours average",
        "Hours", "Lower", ["Government", "Non-Profit / NGO", "Education"],
        ["Adopt e-signature and digital workflows", "Set clear internal SLAs", "Track bottlenecks by department"]),
],

}

GLOSSARY = {
    "KPI": "Key Performance Indicator — a measurable value showing how effectively goals are being achieved.",
    "COGS": "Cost of Goods Sold — the direct costs of producing goods a company sells.",
    "MRR": "Monthly Recurring Revenue — predictable subscription revenue collected every month.",
    "CAC": "Customer Acquisition Cost — the average cost to acquire one new customer.",
    "CLV": "Customer Lifetime Value — total revenue expected from a customer over the full relationship.",
    "NPS": "Net Promoter Score — a measure of customer loyalty based on likelihood to recommend.",
    "CSAT": "Customer Satisfaction Score — a direct survey-based measure of customer happiness.",
    "SLA": "Service Level Agreement — a committed standard of service, e.g. response time.",
    "OEE": "Overall Equipment Effectiveness — a composite score of availability, performance, and quality.",
    "EBITDA": "Earnings Before Interest, Tax, Depreciation, and Amortization — a measure of core operating profit.",
    "ROI": "Return on Investment — the profitability of an investment relative to its cost.",
    "ROAS": "Return on Ad Spend — revenue generated per unit of advertising spend.",
    "DSO": "Days Sales Outstanding — the average number of days it takes to collect payment after a sale.",
    "NRR": "Net Revenue Retention — revenue retained and grown from existing customers over time.",
    "VaR": "Value at Risk — the estimated maximum potential loss over a period at a given confidence level.",
    "NPL": "Non-Performing Loan — a loan that is in default or close to default.",
    "MTTR": "Mean Time to Resolve — the average time taken to resolve an incident.",
}

# ---------------------------------------------------------------------------
# Build KPI objects once at import time, indexed for fast lookup
# ---------------------------------------------------------------------------
KPIS_BY_PROCESS: Dict[str, List[KPI]] = {
    process: [
        KPI(
            key=item["key"], name=item["name"], meaning=item["meaning"],
            why_it_matters=item["why_it_matters"], formula=item["formula"],
            example=item["example"], unit=item["unit"], better=item["better"],
            industries=item.get("industries", []),
            improvement_tips=item.get("improvement_tips", []),
            process=process,
        )
        for item in items
    ]
    for process, items in PROCESS_KPIS.items()
}

_ALL_KPIS: List[KPI] = [k for kpis in KPIS_BY_PROCESS.values() for k in kpis]
_KPI_BY_KEY: Dict[str, KPI] = {k.key: k for k in _ALL_KPIS}


def get_industries() -> List[str]:
    return list(INDUSTRIES)


def get_industry_description(industry: str) -> str:
    return INDUSTRY_DESCRIPTIONS.get(industry, "")


def get_processes_for_industry(industry: str) -> List[str]:
    return list(INDUSTRY_PROCESS_MAPPING.get(industry, []))


def get_all_processes() -> List[str]:
    return sorted(KPIS_BY_PROCESS.keys())


def get_kpis_for_process(process: str) -> List[KPI]:
    return list(KPIS_BY_PROCESS.get(process, []))


def get_all_kpis() -> List[KPI]:
    return list(_ALL_KPIS)


def get_kpi_by_key(key: str) -> Optional[KPI]:
    return _KPI_BY_KEY.get(key)


def get_kpis_for_industry(industry: str) -> List[KPI]:
    kpis: List[KPI] = []
    for process in get_processes_for_industry(industry):
        kpis.extend(get_kpis_for_process(process))
    return kpis


def search_by_keyword(keyword: str) -> List[KPI]:
    kw = keyword.lower()
    return [
        k for k in _ALL_KPIS
        if kw in " ".join([k.name, k.meaning, k.why_it_matters, k.process, k.unit]).lower()
    ]


def filter_kpis(better: Optional[str] = None, unit_contains: Optional[str] = None) -> List[KPI]:
    results = _ALL_KPIS
    if better:
        results = [k for k in results if k.better.lower().startswith(better.lower())]
    if unit_contains:
        results = [k for k in results if unit_contains.lower() in k.unit.lower()]
    return results


def get_glossary() -> Dict[str, str]:
    return dict(GLOSSARY)